export const CONSTANTS = {
  GET_APPS_LIST: "GET_APPS_LIST",
  GET_APPS_LIST_LOADING: "GET_APPS_LIST_LOADING",

  GET_CATEGORY_LIST_LOADING: "GET_CATEGORY_LIST_LOADING",
  GET_CATEGORY_LIST: "GET_CATEGORY_LIST",
};
